# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10processing.proto\x12\tprocessor\"J\n\x08\x43svChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x1c\n\x0f\x66ile_size_bytes\x18\x02 \x01(\x04H\x00\x88\x01\x01\x42\x12\n\x10_file_size_bytes\"\x7f\n\x0eProgressUpdate\x12\x34\n\rstatus_update\x18\x01 \x01(\x0b\x32\x1b.processor.ProcessingStatusH\x00\x12,\n\x07summary\x18\x02 \x01(\x0b\x32\x19.processor.ProcessSummaryH\x00\x42\t\n\x07\x63ontent\"q\n\x10ProcessingStatus\x12\x16\n\x0erows_processed\x18\x01 \x01(\x04\x12\x16\n\x0emalformed_rows\x18\x02 \x01(\x04\x12\x1c\n\x14processed_percentage\x18\x03 \x01(\x02\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x8c\x02\n\x0eProcessSummary\x12\x18\n\x10result_file_name\x18\x01 \x01(\t\x12\x16\n\x0erows_processed\x18\x02 \x01(\x04\x12\x16\n\x0emalformed_rows\x18\x03 \x01(\x04\x12\x1c\n\x14processed_percentage\x18\x04 \x01(\x02\x12\x13\n\x0btotal_sales\x18\x05 \x01(\x04\x12\x1a\n\x12unique_departments\x18\x06 \x01(\x04\x12\x1f\n\x17processing_time_seconds\x18\x07 \x01(\x02\x12$\n\x17storage_result_file_url\x18\x08 \x01(\tH\x00\x88\x01\x01\x42\x1a\n\x18_storage_result_file_url2P\n\x0c\x43svProcessor\x12@\n\nProcessCsv\x12\x13.processor.CsvChunk\x1a\x19.processor.ProgressUpdate(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSVCHUNK']._serialized_start=31
  _globals['_CSVCHUNK']._serialized_end=105
  _globals['_PROGRESSUPDATE']._serialized_start=107
  _globals['_PROGRESSUPDATE']._serialized_end=234
  _globals['_PROCESSINGSTATUS']._serialized_start=236
  _globals['_PROCESSINGSTATUS']._serialized_end=349
  _globals['_PROCESSSUMMARY']._serialized_start=352
  _globals['_PROCESSSUMMARY']._serialized_end=620
  _globals['_CSVPROCESSOR']._serialized_start=622
  _globals['_CSVPROCESSOR']._serialized_end=702
# @@protoc_insertion_point(module_scope)
